#!/bin/bash
export PS1="[\W]$ "
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
alias ls='ls -GFh'
alias ll='ls -lF'
alias l='ls -AlF'
# alias l='ls -CF'


#export ANDROID_NDK=$HOME/Library/Android/ndk-r10e
export ANDROID_HOME=$HOME/Library/Android/sdk
export GOROOT="/usr/local/opt/go/libexec"
export GOPATH=$HOME/.go:$HOME/goProject
export JAVA_HOME=$(/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java_home)
export CLASSPATH=$JAVA_HOME/lib
#export RUBY_HOME=$HOME/.rbenv/versions/2.2.2
#export JIRA_HOME=$HOME/atlassian-jira-6.4.11-standalone/atlassian-jira
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
PATH=$JAVA_HOME/bin:${GOPATH//://bin:}/bin:$HOME/Command:$ANDROID_HOME/platform-tools/:$PATH
